# Generated by Django 5.0 on 2024-02-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_newuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='username',
        ),
    ]
