# Generated by Django 5.0 on 2024-03-12 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_alter_participation_first_phone_and_more'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='user_id',
        ),
        migrations.AddField(
            model_name='payments',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.participation'),
        ),
    ]
