# Generated by Django 5.0 on 2024-02-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_events_event_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
