# Generated by Django 5.0 on 2024-02-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_event_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
