# Generated by Django 5.0 on 2024-03-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_event_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_incharge_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(null=True, upload_to='Home/static'),
        ),
    ]
