# Generated by Django 5.0 on 2024-03-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_event_event_incharge_contact_alter_event_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_genre',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
