# Generated by Django 5.0 on 2024-03-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_event_event_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_genre',
            field=models.CharField(choices=[('Techinical', 'technical'), ('Cultural', 'cultural'), ('Sports', 'sports')], default='sports', max_length=10),
        ),
    ]
