# Generated by Django 5.0 on 2024-03-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_event_event_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry_fees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_rules',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='prize_pool',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='society_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
