# Generated by Django 5.0 on 2024-03-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_event_entry_fees_event_event_rules_event_prize_pool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='particpant_email',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='phone',
        ),
        migrations.AddField(
            model_name='participation',
            name='first_college',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='first_phone',
            field=models.IntegerField(default=9999911111),
        ),
        migrations.AddField(
            model_name='participation',
            name='fourth_college',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='fourth_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='fourth_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='second_college',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='second_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='second_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='team_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='third_college',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='third_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='third_phone',
            field=models.IntegerField(null=True),
        ),
    ]
