# Generated by Django 5.0 on 2024-03-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_alter_participation_first_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='leader_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
