# Generated by Django 5.0 on 2024-03-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_participation_leader_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='payment_success',
            field=models.BooleanField(default=False),
        ),
    ]
