# Generated by Django 5.0 on 2024-03-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_participation_payment_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='leader_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
