# Generated by Django 5.0 on 2024-03-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_alter_participation_leader_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='second_name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
