# Generated by Django 5.0 on 2024-03-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_alter_participation_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='second_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
