# Generated by Django 5.0 on 2024-03-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_alter_participation_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='first_college',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='first_phone',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='participation',
            name='fourth_college',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='fourth_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='fourth_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='leader_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='payment_success',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='participation',
            name='second_college',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='second_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='team_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='third_college',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='third_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='third_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
