# Generated by Django 5.0 on 2024-03-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_alter_participation_first_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='leader_email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
